sudo: required
services:
  - docker

before_install:
  - docker build -t mooreinteractive/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mooreinteractive/react-test npm test -- --coverage

after_success:
  - docker build -t mooreinteractive/multi-client ./client
  - docker build -t mooreinteractive/multi-nginx ./nginx
  - docker build -t mooreinteractive/multi-server ./server
  - docker build -t mooreinteractive/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to aws
  - docker push mooreinteractive/multi-client
  - docker push mooreinteractive/multi-nginx
  - docker push mooreinteractive/multi-server
  - docker push mooreinteractive/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-314480548641
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
